/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BiddingDynamicsList: typeof import('./src/components/Common/BiddingDynamicsList.vue')['default']
    Breadcrumb: typeof import('./src/components/Common/Breadcrumb.vue')['default']
    Dialog: typeof import('./src/components/Common/Dialog/index.vue')['default']
    ExportCanvasDialog: typeof import('./src/components/Business/exportCanvasDialog.vue')['default']
    IndustryInsightList: typeof import('./src/components/Common/IndustryInsightList.vue')['default']
    Loading: typeof import('./src/components/Common/Loading.vue')['default']
    Login: typeof import('./src/components/Business/Login.vue')['default']
    Logout: typeof import('./src/components/Common/Dialog/Logout.vue')['default']
    MiniAppNeed: typeof import('./src/components/Common/Dialog/miniAppNeed.vue')['default']
    OnLineReportList: typeof import('./src/components/Common/OnLineReportList.vue')['default']
    PageBottom: typeof import('./src/components/Business/PageBottom.vue')['default']
    PageNav: typeof import('./src/components/Business/PageNav.vue')['default']
    PolicyList: typeof import('./src/components/Common/PolicyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Common/Select.vue')['default']
  }
}
