/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BiddingDynamicsList: typeof import('./../components/Business/BiddingDynamicsList.vue')['default']
    Breadcrumb: typeof import('./../components/Common/Breadcrumb.vue')['default']
    ConsultationNav: typeof import('./../components/Business/ConsultationNav.vue')['default']
    Dialog: typeof import('./../components/Common/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    ExportCanvasDialog: typeof import('./../components/Business/ExportCanvasDialog.vue')['default']
    IndustryInsightList: typeof import('./../components/Common/IndustryInsightList.vue')['default']
    Loading: typeof import('./../components/Common/Loading.vue')['default']
    Login: typeof import('./../components/Business/Login.vue')['default']
    Logout: typeof import('./../components/Common/Dialog/Logout.vue')['default']
    MembersBuy: typeof import('./../components/Business/MembersBuy.vue')['default']
    MiniAppNeed: typeof import('./../components/Common/Dialog/miniAppNeed.vue')['default']
    OnLineReportList: typeof import('./../components/Business/OnLineReportList.vue')['default']
    OpenVip: typeof import('./../components/Common/Dialog/OpenVip.vue')['default']
    PageBottom: typeof import('./../components/Business/PageBottom.vue')['default']
    PageNav: typeof import('./../components/Business/PageNav.vue')['default']
    Pagination: typeof import('./../components/Common/Pagination.vue')['default']
    PolicyList: typeof import('./../components/Common/PolicyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Common/Search.vue')['default']
    Select: typeof import('./../components/Common/Select.vue')['default']
    SkipMask: typeof import('./../components/Common/SkipMask.vue')['default']
    Tabs: typeof import('./../components/Common/Tabs.vue')['default']
    WhiteReport: typeof import('./../components/Business/WhiteReport.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
